version: "3"
services:
  redis:
    image: redis
    networks: 
      - webnet
  db:
    image: postgres
    # volumes: 
      # - ./pgdata:/var/lib/postgresql/data
    networks: 
      - webnet
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: test
  web:
    image: inblack67/pern:latest
    ports:
      - "80:5000"
    networks:
      - webnet
    depends_on:
      - db
      - redis
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      DB_HOST: db
      REDIS_HOST: redis
      PORT: 5000
networks:
  webnet: